# Generated by Django 4.0.6 on 2022-09-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='category',
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='theme', to='timeline.category'),
        ),
    ]
