# Generated by Django 4.0.6 on 2022-09-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_maincategory_category_active_category_creationtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorystatistics',
            old_name='avarge',
            new_name='average',
        ),
    ]
