# Generated by Django 4.0.6 on 2022-10-01 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_rename_avarge_categorystatistics_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
