# Generated by Django 4.0.6 on 2022-10-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_person_creationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='average',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='plays',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CategoryStatistics',
        ),
    ]
