# Generated by Django 4.0.6 on 2022-10-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_alter_category_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank='Sort the cards according the year of birth.', max_length=1000),
        ),
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.CharField(default='Birth', max_length=60),
        ),
    ]
